/**
 * Усі рядки інтерфейсу. Компоненти не містять тексту для користувача напряму —
 * тільки `S.…`. Мова інтерфейсу — українська; жодних англійських слів
 * посеред українського рядка.
 */

import type {
  AutomationStatus,
  BulkTextField,
  CaseKind,
  CasePriority,
  CaseStatus,
  CoverageKind,
  DefectSeverity,
  DefectStatus,
  ItemStatus,
  ProposalKind,
  ProposalState,
  RunKind,
  RunState,
  SkillName,
  SourceKind,
} from './types';

export const S = {
  app: {
    name: 'Jules',
    sub: 'Реєстр тест-кейсів',
    title: 'Реєстр тест-кейсів',
  },

  nav: {
    dashboard: 'Огляд',
    cases: 'Реєстр кейсів',
    proposals: 'Погодження',
    runs: 'Прогони',
    coverage: 'Покриття вимог',
    settings: 'Налаштування',
    open: 'Відкрити навігацію',
    close: 'Закрити навігацію',
    aria: 'Основна навігація',
    groupOverview: 'Стан справ',
    groupCycle: 'Цикл тестування',
    groupAnalysis: 'Аналітика',
    groupSystem: 'Система',
    hintDashboard: 'Що зараз із тестуванням і що потребує вашого рішення',
    hintCases: 'Усі тест-кейси: створити, відредагувати, зібрати в прогін',
    hintProposals: 'Що пропонує AI — нічого не входить у реєстр без вашого «так»',
    hintRuns: 'Запуски кейсів і наборів та їхні результати',
    defects: 'Дефекти',
    hintDefects: 'Знайдені проблеми продукту: розібрати, закрити, звʼязати з кейсом',
    hintCoverage: 'Які вимоги з документів уже покриті кейсами, а які ні',
    hintSettings: 'Підключення до моделі, TestRail і Confluence',
  },

  common: {
    loading: 'Завантаження…',
    retry: 'Спробувати ще',
    cancel: 'Скасувати',
    close: 'Закрити',
    save: 'Зберегти',
    saved: 'Збережено',
    apply: 'Застосувати',
    add: 'Додати',
    remove: 'Видалити',
    edit: 'Редагувати',
    search: 'Пошук',
    searchPlaceholder: 'Пошук за назвою, перевірками, тегами…',
    all: 'Усі',
    none: '—',
    yes: 'Так',
    no: 'Ні',
    total: 'Усього',
    of: 'з',
    page: 'Сторінка',
    prev: 'Назад',
    next: 'Далі',
    up: 'Вгору',
    down: 'Вниз',
    undo: 'Відкотити',
    copy: 'Скопіювати',
    copied: 'Скопійовано',
    refresh: 'Оновити',
    reset: 'Скинути',
    filters: 'Фільтри',
    resetFilters: 'Скинути фільтри',
    selected: 'Вибрано',
    selectAll: 'Вибрати всі на сторінці',
    selectRow: 'Вибрати рядок',
    expand: 'Розгорнути',
    collapse: 'Згорнути',
    export: 'Експорт',
    details: 'Деталі',
    openLink: 'Відкрити',
    never: 'ніколи',
    unknown: 'невідомо',
    dismiss: 'Приховати',
    theme: 'Тема',
    themeLight: 'Світла тема',
    themeDark: 'Темна тема',
    keyboardHelp: 'Довідка по клавішах',
    project: 'Проєкт',
    mockMode: 'Режим фікстур (без бекенду)',
  },

  errors: {
    generic: 'Не вдалося виконати запит.',
    network: 'Сервер не відповідає. Перевірте, що бекенд запущено на порту 3840.',
    notFound: 'Не знайдено: сервер відповів 404. Можливо, цей ендпоінт ще не реалізований.',
    badRequest: 'Сервер відхилив запит (400). Перевірте введені дані.',
    conflict: 'Конфлікт (409): дані змінилися або запис не можна видалити.',
    server: 'Помилка на сервері (5xx).',
    upstream: 'Зовнішній сервіс недоступний (502).',
    unauthorized: 'Потрібна авторизація. Додайте токен у Налаштуваннях.',
    parse: 'Сервер повернув не JSON.',
    aborted: 'Запит скасовано.',
    title: 'Не вдалося завантажити',
    boundaryTitle: 'Інтерфейс зламався',
    boundaryHint: 'Це помилка в самому інтерфейсі. Перезавантажте сторінку; якщо повториться — покажіть текст нижче розробнику.',
    reload: 'Перезавантажити сторінку',
    routeTitle: 'Сторінки не існує',
    routeHint: 'Перевірте адресу або повертайтеся на дашборд.',
    toDashboard: 'На дашборд',
  },

  empty: {
    cases: 'У цій секції ще немає кейсів',
    casesHint: 'Послабте фільтри — або згенеруйте кейси з вимог на екрані «Покриття вимог».',
    proposals: 'Немає чого погоджувати',
    proposalsHint: 'Пропозиції зʼявляться, коли AI опрацює документи: екран «Покриття вимог» → «Згенерувати кейси» або «Перевірити покриття».',
    runs: 'Прогонів ще не було',
    runsHint: 'Створіть прогін з реєстру: виберіть кейси й натисніть «Створити прогін».',
    runItems: 'У прогоні немає кейсів',
    runItemsHint: 'Прогін створено без кейсів. Створіть новий з непорожньої вибірки.',
    sources: 'Документів із вимогами немає',
    sourcesHint: 'Імпортуйте сторінку Confluence за посиланням або просто вставте текст вимог.',
    coverage: 'Документів із вимогами ще немає',
    coverageHint: 'Імпортуйте сторінку Confluence за посиланням або вставте текст вимог — із них AI запропонує кейси.',
    mappings: 'Правил вивантаження в TestRail ще немає',
    mappingsHint: 'Правило описує, у які поля TestRail лягають наші поля при вивантаженні.',
    skillRuns: 'AI ще нічого не робив для цього проєкту',
    skillRunsHint: 'Журнал заповнюється після запуску генерації кейсів чи перевірки покриття.',
    tree: 'Модулів ще немає',
    treeHint: 'Модуль — це частина продукту (пошук, каталог, вхід). Створіть перший, щоб додавати в нього кейси.',
    flaky: 'Нестабільних кейсів не знайдено',
    flakyHint: 'Показник нестабільності рахується за автопрогонами.',
    decisions: 'Рішень не потрібно',
    decisionsHint: 'Нічого не чекає на вас: усі пропозиції розглянуті, розбіжностей із TestRail немає, відкритих дефектів теж.',
    history: 'Історія порожня',
    historyHint: 'Ревізії з’являються після першої зміни кейса.',
    logs: '(очікування виводу рушія…)',
    defects: 'Дефектів немає',
    defectsHint: 'Дефект зʼявиться сам, коли прогін знайде підтверджену проблему, або коли ви заведете його під час ручного прогону.',
  },

  dashboard: {
    title: 'Огляд',
    sub: 'Що зараз із тестуванням і що чекає на ваше рішення',
    decisions: 'Черга рішень',
    decisionsSub: 'Що чекає на інженера',
    proposalsPending: 'Пропозиції AI на розгляд',
    drift: 'Розбіжності з TestRail',
    openDefects: 'Відкриті дефекти',
    kpiCases: 'Кейсів усього',
    kpiCoverage: 'Покриття вимог',
    kpiAutomation: 'Автоматизація',
    kpiPassRate: 'Успішність за 7 днів',
    kpiRuns7d: 'Прогонів за 7 днів',
    kpiOpenRuns: 'Відкритих прогонів',
    byStatus: 'Кейси за статусом',
    byAutomation: 'Кейси за автоматизацією',
    byPriority: 'Кейси за пріоритетом',
    modules: 'Зведення за модулями',
    moduleName: 'Модуль',
    moduleCases: 'Кейсів',
    moduleAutomated: 'Автоматизовано',
    modulePassRate: 'Успішність',
    moduleGaps: 'Прогалин',
    flaky: 'Топ нестабільних кейсів',
    flakeScore: 'Нестабільність',
    lastResult: 'Останній результат',
    recentRuns: 'Останні прогони',
    coverageBlocks: 'блоків вимог',
    coverageCovered: 'покрито',
    coverageGaps: 'прогалин',
    derivedShare: 'частка домислів AI',
    cycle: 'Як влаштована робота',
    cycleSub: 'Пʼять кроків від документа до результату — цифри показують, де ви зараз',
    cycleDocs: 'Вимоги з документів',
    cycleDocsNote: (covered: number, total: number) => `${covered} з ${total} блоків покрито кейсами`,
    cycleDocsEmpty: 'Документи ще не завантажені',
    cycleCases: 'Тест-кейси',
    cycleCasesNote: (approved: number, total: number) => `${approved} з ${total} затверджені`,
    cycleReview: 'Погодження людиною',
    cycleReviewNote: (n: number) => (n > 0 ? `${n} чекає на ваше рішення` : 'Усе розглянуто'),
    cycleAutomation: 'Скрипти',
    cycleAutomationNote: (auto: number, total: number) => `${auto} з ${total} кейсів мають автоскрипт`,
    cycleRuns: 'Прогони і результати',
    cycleRunsNote: (runs: number) => (runs > 0 ? `${runs} за останні 7 днів` : 'За 7 днів прогонів не було'),
    goCases: 'Перейти в реєстр',
    goProposals: 'Переглянути пропозиції',
    goCoverage: 'Відкрити покриття',
  },

  cases: {
    title: 'Реєстр тест-кейсів',
    sub: 'Усі перевірки продукту. Виберіть кейси — і зберіть із них прогін',
    tree: 'Модулі',
    treeAll: 'Усі кейси',
    includeSubsections: 'Разом із вкладеними',
    colId: 'ID',
    colTitle: 'Назва',
    colSection: 'Модуль',
    colKind: 'Тип',
    colPriority: 'Пріоритет',
    colStatus: 'Статус',
    colAutomation: 'Скрипт',
    colTags: 'Теги',
    colCoverage: 'Покриття',
    colLastResult: 'Результат',
    colUpdated: 'Оновлено',
    filterSection: 'Модуль',
    filterTags: 'Теги (через кому)',
    filterKind: 'Тип',
    filterPriority: 'Пріоритет',
    filterStatus: 'Статус',
    filterAutomation: 'Автоматизація',
    filterQ: 'Пошук',
    sortBy: 'Сортування',
    sortAsc: 'за зростанням',
    sortDesc: 'за спаданням',
    bulkTitle: 'Масові дії',
    bulkReplace: 'Замінити текст',
    bulkPriority: 'Пріоритет',
    bulkKind: 'Тип',
    bulkStatus: 'Статус',
    bulkAddTag: 'Додати тег',
    bulkMove: 'Перемістити',
    bulkAutomation: 'Автоматизація',
    bulkExport: 'Експорт',
    bulkCreateRun: 'Створити прогін',
    bulkOffPage: (n: number) => `з них поза цією сторінкою: ${n}`,
    bulkClear: 'Зняти вибір',
    detailTitle: 'Деталі кейса',
    detailPick: 'Виберіть кейс у таблиці',
    detailPickHint: 'Натисніть рядок або рухайтеся клавішами j / k.',
    preconditions: 'Передумови',
    checks: 'Перевірки',
    checksAdd: 'Додати перевірку',
    checksNew: 'Нова перевірка',
    checkUp: 'Перемістити вище',
    checkDown: 'Перемістити нижче',
    checkDelete: 'Видалити перевірку',
    tags: 'Теги',
    tagNew: 'Новий тег',
    requirement: 'Зв’язок із вимогою',
    requirementQuote: 'цитата вимоги',
    requirementDerived: 'домисел AI',
    tabHistory: 'Історія',
    tabAutomation: 'Автоматизація',
    revisions: 'Ревізії',
    results: 'Результати прогонів',
    revisionVersion: 'Версія',
    revisionAuthor: 'Автор',
    revisionReason: 'Причина',
    scenario: 'Сценарій',
    scenarioNone: 'Сценарій не прив’язано',
    lastAutoRun: 'Останній автопрогін',
    quarantine: 'Карантин',
    quarantineReason: 'Причина карантину',
    automationSave: 'Зберегти автоматизацію',
    version: 'Версія',
    owner: 'Власник',
    updated: 'Оновлено',
    created: 'Створено',
    openRun: 'Відкрити прогін',
    saveCase: 'Зберегти кейс',
    unsaved: 'Є незбережені зміни',
  },

  replace: {
    title: 'Масова заміна тексту',
    find: 'Знайти',
    replace: 'Замінити на',
    fields: 'Поля',
    regex: 'Регулярний вираз',
    caseSensitive: 'Враховувати регістр',
    count: 'Порахувати',
    counting: 'Рахуємо…',
    previewTitle: 'Що зміниться',
    colCase: 'Кейс',
    colField: 'Поле',
    colBefore: 'Було',
    colAfter: 'Стало',
    colCount: 'Входжень',
    summary: (cases: number, occ: number) => `Кейсів: ${cases} · Входжень: ${occ}`,
    applyBtn: 'Застосувати',
    applying: 'Застосовуємо…',
    noMatches: 'Нічого не знайдено — заміну застосовувати нема до чого.',
    needCount: 'Спершу натисніть «Порахувати», щоб побачити розбіжності.',
    appliedToast: (n: number) => `Заміну застосовано до ${n} кейсів`,
    undoneToast: 'Заміну відкочено',
    undoFailed: 'Не вдалося відкотити заміну',
    reasonLabel: 'Причина зміни (у ревізію)',
    reasonPlaceholder: 'напр. перейменування терміна за рішенням аналітика',
    scopeSelected: (n: number) => `Область: вибрані кейси (${n})`,
    scopeFilter: 'Область: усі кейси за поточним фільтром',
  },

  proposals: {
    title: 'Погодження',
    sub: 'Що пропонує AI. У реєстр нічого не потрапляє, поки ви не погодите',
    filterState: 'Стан',
    filterKind: 'Тип',
    filterSource: 'Джерело вимог',
    approveSelected: 'Погодити вибрані',
    rejectSelected: 'Відхилити вибрані',
    editBefore: 'Виправити перед погодженням',
    saveEdit: 'Зберегти правку',
    cancelEdit: 'Скасувати правку',
    showDiff: 'Показати зміни',
    hideDiff: 'Сховати зміни',
    rationale: 'Чому AI це пропонує',
    origin: 'Джерело',
    originBlock: 'Блок вимоги',
    originDerived: 'Домисел AI (у вимозі цього немає)',
    originQuote: 'Цитата вимоги',
    originSkill: 'Що робив AI',
    originRun: 'Прогін',
    originCase: 'Кейс',
    rejectNote: 'Причина відхилення',
    rejectNotePlaceholder: 'напр. дублює CYBER-REG-004',
    approvedToast: (n: number) => `Погоджено пропозицій: ${n}`,
    rejectedToast: (n: number) => `Відхилено пропозицій: ${n}`,
    editedToast: 'Правку збережено',
    partialErrors: (n: number) => `З помилками: ${n}`,
    editTitle: 'Назва кейса',
    editChecks: 'Перевірки (по одній на рядок)',
    payloadRaw: 'Дані пропозиції',
    confirmTitle: 'Погодити пропозиції?',
    confirmBody: 'Після погодження це одразу зʼявиться в реєстрі:',
    confirmApprove: (n: number) => `Так, погодити (${n})`,
    confirmHint: 'Скасувати погодження одним рухом не можна — кейси доведеться правити вручну.',
  },

  autoRun: {
    tabChecklist: 'Чек-лист',
    tabResults: 'Результати рушія',
    target: 'Куди справді пішов прогін',
    requested: 'не пішли на',
    requestedHint: 'Ця адреса програла вибір цілі: або її перекрило середовище прогону, або власна ціль сценарію.',
    passed: 'кроків пройдено',
    failed: 'впало',
    healed: 'полікувано',
    healedHint: 'Крок вдався не з першого разу: елемент знайшовся після повторної спроби.',
    healedShort: (n: number) => `самолікування ×${n}`,
    skipped: 'не дійшли',
    modelCalls: 'звернень до моделі',
    modelCallsHint: '«—» означає, що порахувати не вдалося, а не нуль звернень.',
    noSteps: 'Рушій не встиг записати кроки.',
    kindStep: 'крок',
    kindAssertion: 'перевірка',
    status: {
      passed: 'пройдено',
      failed: 'впало',
      healed: 'полікувано',
      skipped: 'не дійшли',
    } as Record<'passed' | 'failed' | 'healed' | 'skipped', string>,
    defects: 'Що рушій вважає дефектом',
    confirmed: 'підтверджено',
    unconfirmed: 'під питанням',
    contradicted: 'Суперечить вердикту',
    noAuto: 'Автопрогону для цього кейса не було',
  },

  defects: {
    title: 'Дефекти',
    sub: 'Що зламано в продукті: знайдене прогонами й заведене вручну, без дублів',
    filterStatus: 'Стан',
    colTitle: 'Дефект',
    colSeverity: 'Серйозність',
    colStatus: 'Стан',
    colCase: 'Кейс',
    colSeen: 'Разів',
    colLastSeen: 'Востаннє',
    details: 'Деталі',
    noDetails: 'Опису немає',
    firstSeen: 'Уперше помічено',
    external: 'Зовнішній ключ',
    seenHint: 'Скільки прогонів побачили той самий дефект. Одиниця — ще не система, кілька — стабільна проблема.',
    caseFilter: (caseId: string) => `Лише кейс ${caseId}`,
    savedToast: 'Дефект оновлено',
  },

  runs: {
    title: 'Прогони',
    sub: 'Запуски кейсів і наборів: ручні та автоматичні — в одній історії',
    create: 'Новий прогін',
    createTitle: 'Створити прогін',
    runTitle: 'Назва прогону',
    runTitlePlaceholder: 'напр. Регрес реєстру 30.09',
    runKind: 'Тип',
    baseUrl: 'Адреса середовища',
    baseUrlHint: 'Порожньо — кожен кейс іде на адресу зі свого сценарію. Заповнено — весь прогін піде сюди (стейдж, копія продакшена).',
    envLabel: 'Позначка середовища',
    engineMode: 'Режим рушія',
    colTitle: 'Назва',
    colKind: 'Тип',
    colState: 'Стан',
    colStarted: 'Початок',
    colProgress: 'Прогрес',
    colSummary: 'Результати',
    filterKind: 'Тип',
    filterState: 'Стан',
    checklist: 'Чек-лист прогону',
    progress: 'Прогрес',
    complete: 'Завершити прогін',
    rerunFailed: 'Перезапустити впалі',
    runAuto: 'Запустити автоматизовані',
    commentLabel: 'Коментар',
    commentPlaceholder: 'Що саме не так, кроки відтворення…',
    defectTitle: 'Чернетка дефекту',
    defectLink: 'Є дефект — відкрити',
    defectTitleLabel: 'Назва дефекту',
    defectSeverity: 'Серйозність',
    defectCreate: 'Створити дефект разом зі статусом',
    saveItem: 'Зберегти результат',
    engineLogs: 'Логи рушія',
    engineConnecting: 'Підключення до потоку логів…',
    engineLive: 'Потік активний',
    engineClosed: 'Потік завершено',
    engineRetrying: (s: number) => `Зв’язок втрачено, повтор за ${s} с…`,
    engineReconnect: 'Перепідключитися',
    engineNoRun: 'Автопрогону для цього кейса ще не було',
    autoRun: 'Автопрогін',
    keyboardHint: 'Клавіші: 1 — пройдено, 2 — впало, 3 — заблоковано, 4 — пропущено, Enter/j — далі, k — назад',
    completedToast: 'Прогін завершено',
    autoStartedToast: (n: number) => `У чергу рушія поставлено кейсів: ${n}`,
    rerunToast: 'Створено прогін із впалих кейсів',
    createdToast: 'Прогін створено',
    itemSavedToast: 'Результат збережено',
    finished: 'Завершено',
    started: 'Початок',
    executor: 'Виконавець',
    note: 'Примітка',
    noAutomated: 'Серед кейсів прогону немає автоматизованих',
    cursorHint: 'Поточний кейс',
    targetsFromScenarios: 'цілі зі сценаріїв',
    closedHint: 'Прогін завершено — нові результати в нього не пишуться',
  },

  coverage: {
    title: 'Покриття вимог',
    sub: 'Звідки беруться кейси: документ розбивається на вимоги, і видно, які з них ще ніхто не перевіряє',
    sources: 'Джерела вимог',
    import: 'Імпортувати вимоги',
    importTitle: 'Імпорт джерела вимог',
    importKind: 'Тип джерела',
    importUrl: 'URL сторінки Confluence',
    importUrlPlaceholder: 'https://…/wiki/spaces/…/pages/…',
    importText: 'Текст вимог',
    importTextPlaceholder: 'Вставте текст вимог. Порожній рядок розділяє блоки.',
    importTitleField: 'Назва джерела',
    importSubmit: 'Імпортувати',
    importedToast: (n: number) => `Документ розібрано на вимоги: ${n}`,
    refresh: 'Перезавантажити джерело',
    refreshedToast: (c: number, a: number, r: number) =>
      `Змінено: ${c}, додано: ${a}, прибрано: ${r}`,
    changedBadge: 'Змінилось у джерелі',
    matrix: 'Вимога → кейси, які її перевіряють',
    colBlock: 'Вимога з документа',
    colCases: 'Кейси',
    colState: 'Стан',
    gap: 'Ніхто не перевіряє',
    covered: 'Покрито',
    writeCases: 'Згенерувати кейси',
    writeCasesRunning: 'Генеруємо…',
    writeCasesFor: (n: number) => `Згенерувати кейси (вимог: ${n})`,
    needBlocks: 'Спершу відмітьте вимоги в таблиці нижче',
    needSection: 'Виберіть модуль, у який класти нові кейси',
    validate: 'Перевірити покриття',
    validateRunning: 'Перевіряємо…',
    writeCasesToast: (n: number) => `Створено пропозицій: ${n}. Перейдіть у «Погодження».`,
    validateToast: (gaps: number, dup: number) => `Прогалин: ${gaps}, дублів: ${dup}`,
    pickSource: 'Джерело',
    selectBlocks: 'Виберіть вимоги, з яких генерувати кейси',
    selectedBlocks: (n: number) => `Вибрано вимог: ${n}`,
    targetSection: 'Модуль для нових кейсів',
    maxPerBlock: 'Максимум кейсів на блок',
    includeDerived: 'Дозволити домисли AI (негативні, безпекові)',
    statsLine: (blocks: number, covered: number, gaps: number) =>
      `Вимог: ${blocks} · Покрито кейсами: ${covered} · Не перевіряється: ${gaps}`,
    blockChangeNew: 'новий',
    blockChangeChanged: 'змінений',
    blockChangeRemoved: 'прибраний',
    blockChangeSame: 'без змін',
    report: 'Звіт перевірки',
    reportGaps: 'Прогалини',
    reportDuplicates: 'Дублі',
    reportUntestable: 'Неперевірюване',
    reportContradictions: 'Суперечності',
  },

  settings: {
    title: 'Налаштування',
    sub: 'Проєкт, підключення до моделі та зовнішніх систем, типові параметри прогонів',
    projectSection: 'Проєкт',
    projectName: 'Назва',
    projectKey: 'Префікс ID кейсів',
    projectBaseUrl: 'Базовий URL застосунку',
    projectSpace: 'Простір Confluence',
    integrations: 'Підключення',
    intLlm: 'Модель (LLM)',
    intConfluence: 'Confluence',
    intConfluenceNoSpace: 'Ключі є, але в проєкті не заданий простір Confluence — вкажіть його вище.',
    intTestrail: 'TestRail',
    intConfigured: 'Налаштовано',
    intMissing: 'Не налаштовано',
    intChecking: 'Перевірка…',
    intLlmCheck: 'Перевірити модель',
    intModels: 'Доступні моделі',
    intRoles: 'Моделі за ролями',
    intRolesHint:
      'Jules використовує три адреси моделі: виконання сценаріїв, генерація кейсів і перевірка згенерованого. Якщо одна з них лежить, впаде лише відповідний крок.',
    colRole: 'Роль',
    colEndpoint: 'Адреса',
    roleOk: 'відповідає',
    roleFail: 'недоступна',
    roleNotSet: 'не задана',
    modelMissing: 'моделі немає на цьому сервері',
    intConfluenceHint: 'Налаштовується змінними середовища на сервері; імпорт за URL працює тільки з ними.',
    intTestrailHint: 'Потрібні TESTRAIL_BASE_URL, TESTRAIL_USER, TESTRAIL_API_KEY. Без них доступні лише CSV і XML.',
    mappings: 'Правила вивантаження в TestRail',
    mappingName: 'Назва правила',
    mappingTemplate: 'Шаблон',
    mappingTemplateChecklist: 'Чек-лист в одному полі',
    mappingTemplateSteps: 'Окремі кроки',
    mappingIdField: 'Поле для нашого ID',
    mappingDelimiter: 'Розділювач',
    mappingCreate: 'Додати профіль',
    mappingSaved: 'Профіль збережено',
    runDefaults: 'Типові параметри прогонів',
    tabProject: 'Проєкт і доступ',
    tabIntegrations: 'Підключення',
    tabRuns: 'Прогони і робота AI',
    defaultUrl: 'Запасна адреса для сценаріїв без власної цілі',
    defaultUrlHint: 'Використовується, лише коли у сценарію немає `target_url` і прогін не закріпив своє середовище.',
    defaultMode: 'Режим рушія',
    modeWarmUp: 'Перший запуск (AI вчить локатори)',
    modeRegression: 'Регресія (кеш локаторів)',
    defaultScenario: 'Сценарій за замовчуванням',
    debugCache: 'Докладний лог кешу локаторів',
    skillLog: 'Журнал роботи AI',
    colSkill: 'Дія AI',
    colState: 'Стан',
    colModel: 'Модель',
    colTokens: 'Токени',
    colDuration: 'Час',
    colProposals: 'Пропозицій',
    colStarted: 'Запуск',
    access: 'Доступ',
    apiToken: 'Токен API (Bearer)',
    apiTokenHint: 'Зберігається лише у localStorage цього браузера й додається до кожного запиту.',
    userName: 'Ваше ім’я (для авторства змін)',
    userNameHint: 'Іде в заголовку X-Jules-User; сервер пише його в author / updatedBy.',
    savedToast: 'Налаштування збережено',
  },

  keys: {
    title: 'Клавіатура',
    slash: 'Фокус у пошук',
    jk: 'Наступний / попередній рядок',
    space: 'Вибрати рядок',
    enter: 'Відкрити / далі',
    esc: 'Закрити діалог або шухляду',
    question: 'Ця довідка',
    digits: 'Статус кейса у прогоні: пройдено / впало / заблоковано / пропущено',
    hintOpen: 'Натисніть ? для довідки по клавішах',
  },
} as const;

/* ───────────────────────── підписи перелічень ────────────────────────── */

export const caseKindLabel: Record<CaseKind, string> = {
  positive: 'позитивний',
  negative: 'негативний',
  neutral: 'нейтральний',
  security: 'безпека',
  a11y: 'доступність',
  performance: 'швидкодія',
};

/** Короткі підписи для щільних таблиць. Повні лишаються у фільтрах і деталях кейса. */
export const caseKindShort: Record<CaseKind, string> = {
  positive: 'позитив',
  negative: 'негатив',
  neutral: 'нейтрал',
  security: 'безпека',
  a11y: 'a11y',
  performance: 'швидкодія',
};

export const automationStatusShort: Record<AutomationStatus, string> = {
  manual: 'вручну',
  candidate: 'кандидат',
  automated: 'авто',
  quarantined: 'карантин',
};

export const casePriorityLabel: Record<CasePriority, string> = {
  P1: 'P1 — критичний',
  P2: 'P2 — високий',
  P3: 'P3 — середній',
  P4: 'P4 — низький',
};

export const caseStatusLabel: Record<CaseStatus, string> = {
  draft: 'чернетка',
  in_review: 'на рев’ю',
  approved: 'затверджений',
  deprecated: 'застарілий',
};

export const automationStatusLabel: Record<AutomationStatus, string> = {
  manual: 'вручну',
  candidate: 'кандидат',
  automated: 'автоматизований',
  quarantined: 'у карантині',
};

export const itemStatusLabel: Record<ItemStatus, string> = {
  untested: 'не перевірено',
  passed: 'пройдено',
  failed: 'впало',
  blocked: 'заблоковано',
  skipped: 'пропущено',
};

export const runKindLabel: Record<RunKind, string> = {
  manual: 'ручний',
  auto: 'автоматичний',
  mixed: 'змішаний',
};

export const runStateLabel: Record<RunState, string> = {
  open: 'відкритий',
  completed: 'завершений',
  cancelled: 'скасований',
};

export const proposalKindLabel: Record<ProposalKind, string> = {
  case_create: 'новий кейс',
  case_update: 'оновлення кейса',
  case_delete: 'видалення кейса',
  bulk_edit: 'масова правка',
  locator_update: 'локатор',
};

export const proposalStateLabel: Record<ProposalState, string> = {
  pending: 'очікує',
  approved: 'затверджено',
  rejected: 'відхилено',
};

export const coverageKindLabel: Record<CoverageKind, string> = {
  quote: 'цитата вимоги',
  derived: 'домисел AI',
};

export const sourceKindLabel: Record<SourceKind, string> = {
  confluence: 'Confluence',
  file: 'файл',
  paste: 'вставлений текст',
};

export const defectSeverityLabel: Record<DefectSeverity, string> = {
  low: 'низька',
  medium: 'середня',
  high: 'висока',
  critical: 'критична',
};

export const defectStatusLabel: Record<DefectStatus, string> = {
  open: 'відкритий',
  triaged: 'розібраний',
  fixed: 'виправлений',
  wontfix: 'не виправляємо',
  duplicate: 'дубль',
};

export const skillNameLabel: Record<SkillName, string> = {
  'write-cases': 'генерація кейсів',
  'validate-coverage': 'перевірка покриття',
  'format-export': 'експорт',
};

export const skillRunStateLabel: Record<'running' | 'done' | 'failed', string> = {
  running: 'виконується',
  done: 'готово',
  failed: 'помилка',
};

export const bulkFieldLabel: Record<BulkTextField, string> = {
  title: 'назва',
  checks: 'перевірки',
  preconditions: 'передумови',
  steps: 'кроки',
};

export const caseSortLabel: Record<string, string> = {
  id: 'ID',
  title: 'назва',
  updatedAt: 'дата оновлення',
  priority: 'пріоритет',
};
